# Generated by Django 5.2.13 on 2026-05-12 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileLaunchScriptPatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sha256', models.CharField(help_text='SHA256 of the script body the EC2 instance reported on-disk.', max_length=64)),
                ('bytes_written', models.PositiveIntegerField()),
                ('restart_requested', models.BooleanField(help_text='Whether the request asked the controller to restart the runner unit.')),
                ('instance_id', models.CharField(help_text='EC2 instance the patch targeted at the time of the call.', max_length=32)),
                ('ami_version', models.CharField(blank=True, default='', help_text='ACE_MOBILE_AMI_VERSION at the time of the call (best-effort).', max_length=64)),
                ('user', models.ForeignKey(help_text='The authenticated user (PAT or session) who issued the patch.', on_delete=django.db.models.deletion.PROTECT, related_name='mobile_launch_patches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mobile_launch_script_patch',
                'ordering': ['-created_at'],
            },
        ),
    ]
