# Generated by Django 5.2.18 on 2026-10-08 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_by_email', models.CharField(blank=True, default='', max_length=254)),
                ('target_email', models.CharField(max_length=254)),
                ('old_is_staff', models.BooleanField()),
                ('new_is_staff', models.BooleanField()),
                ('source', models.CharField(default='api', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'site_admin_staff_changes',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
