/**
 * GENERATED — do not edit. Run `npm run gen:canopy-api`.
 *
 * Types for the slice of canopy-web's API that ace-web consumes, generated from
 * canopy's own OpenAPI schema so the two cannot describe one contract twice.
 * See scripts/gen-canopy-contract.mjs for why this is pruned and what the
 * allowlist means.
 *
 * NOT ace-web's own API — that is src/api/generated.ts.
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/canopy/api/canopy-sessions/": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List sessions (web + runner-discovered) */
        readonly get: operations["apps_canopy_sessions_api_list_sessions"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canopy/api/canopy-sessions/{session_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get a session + transcript tail */
        readonly get: operations["apps_canopy_sessions_api_get_session"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canopy/api/canopy-sessions/{session_id}/messages": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Load earlier transcript (scroll-back) */
        readonly get: operations["apps_canopy_sessions_api_list_messages"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canopy/api/canopy-sessions/{session_id}/attach": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Attach a viewer (start live streaming) */
        readonly post: operations["apps_canopy_sessions_api_attach_session"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canopy/api/canopy-sessions/{session_id}/detach": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Detach a viewer (stop when last leaves) */
        readonly post: operations["apps_canopy_sessions_api_detach_session"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canopy/api/canopy-sessions/{session_id}/place": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Re-pin a session's oldest queued turn to a runner */
        readonly post: operations["apps_canopy_sessions_api_place"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canopy/api/canopy-sessions/{session_id}/page-state": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        /**
         * Declare what the attached page is showing
         * @description Called by the page as it mounts and whenever its view changes.
         *
         *     Replaces the declaration wholesale. A state larger than the server's cap is
         *     rejected with `too_large`: send the selection (ids, filters) and the tool
         *     that resolves it, not the rows themselves.
         */
        readonly put: operations["apps_canopy_sessions_api_declare_page_state"];
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canopy/api/harness/runners/": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List the fleet I can see
         * @description The supervisor's runner status, and the fleet read every preflight makes.
         *
         *     Scoped by TENANT (`_runner_read_q`), not by who paired what: a member who
         *     paired nothing used to list nothing, which reads identically to "this
         *     workspace has no runners" and is the wrong answer to draw a conclusion from.
         *     Each row carries `can_manage` for the ownership half. Retired runners are
         *     excluded at lookup, as everywhere else.
         */
        readonly get: operations["apps_harness_api_list_runners"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canopy/api/harness/sessions": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List Sessions
         * @description Open emdash sessions the caller can see — across their workspaces, live runners
         *     only, newest-first. Drives the phone's Open Sessions list.
         */
        readonly get: operations["apps_harness_api_list_sessions"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canopy/api/harness/turns/": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List Turns */
        readonly get: operations["apps_harness_api_list_turns"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canopy/api/harness/turns/{turn_id}/events": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Read Turn Events */
        readonly get: operations["apps_harness_api_read_turn_events"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** SessionDetailOut */
        readonly SessionDetailOut: {
            /**
             * Backfill Pending
             * @default false
             */
            readonly backfill_pending: boolean;
            /**
             * Id
             * Format: uuid
             */
            readonly id: string;
            /** Agent Slug */
            readonly agent_slug: string | null;
            /** Project */
            readonly project: string;
            /** Workspace */
            readonly workspace: string;
            /** Title */
            readonly title: string;
            /** Status */
            readonly status: string;
            /**
             * Created At
             * Format: date-time
             */
            readonly created_at: string;
            /**
             * Last Activity At
             * Format: date-time
             */
            readonly last_activity_at: string;
            /**
             * Origin
             * @default web
             */
            readonly origin: string;
            /**
             * Running
             * @default false
             */
            readonly running: boolean;
            /** Runner Name */
            readonly runner_name?: string | null;
            /** Runner Location */
            readonly runner_location?: string | null;
            /** Runner Online */
            readonly runner_online?: boolean | null;
            /** Runner Status */
            readonly runner_status?: string | null;
            /**
             * Session Key
             * @default
             */
            readonly session_key: string;
            /**
             * Waiting On You
             * @default false
             */
            readonly waiting_on_you: boolean;
            /** Messages */
            readonly messages: readonly components["schemas"]["MessageOut"][];
            /** Menu */
            readonly menu?: {
                readonly [key: string]: unknown;
            } | null;
            /**
             * Has More Before
             * @default false
             */
            readonly has_more_before: boolean;
            /** Oldest Loaded Turn Index */
            readonly oldest_loaded_turn_index?: number | null;
        };
        /**
         * DrillRollup
         * @description Aggregated readiness-drill outcomes for one runner, across all its
         *     (runner, agent) drill pairs — the supervisor's at-a-glance signal, without
         *     a client-side fetch-and-reduce over /runners/{id}/drills.
         */
        readonly DrillRollup: {
            /** Passed */
            readonly passed: number;
            /** Failed */
            readonly failed: number;
            /** Pending */
            readonly pending: number;
            /** Last Finished At */
            readonly last_finished_at: string | null;
        };
        /** RunnerOut */
        readonly RunnerOut: {
            /**
             * Id
             * Format: uuid
             */
            readonly id: string;
            /** Name */
            readonly name: string;
            /** Kind */
            readonly kind: string;
            /** Status */
            readonly status: string;
            /** Status Note */
            readonly status_note: string;
            /** Ready */
            readonly ready: boolean;
            /** Ready Note */
            readonly ready_note: string;
            /** Paused */
            readonly paused: boolean;
            /** Paused Note */
            readonly paused_note: string;
            /** Paused At */
            readonly paused_at: string | null;
            /** Last Heartbeat At */
            readonly last_heartbeat_at: string | null;
            /** Capabilities */
            readonly capabilities: {
                readonly [key: string]: unknown;
            };
            /** Host */
            readonly host: string;
            /** Code Branch */
            readonly code_branch: string;
            /** Code Version */
            readonly code_version: string;
            /** Code Sha */
            readonly code_sha: string;
            /** Expected Code Sha */
            readonly expected_code_sha: string;
            /** Code Committed At */
            readonly code_committed_at: number;
            /** Expected Code Committed At */
            readonly expected_code_committed_at: number;
            /** Workspace */
            readonly workspace: string | null;
            /** Paired By Email */
            readonly paired_by_email: string | null;
            /**
             * Can Manage
             * @default true
             */
            readonly can_manage: boolean;
            /**
             * Can Administer
             * @default true
             */
            readonly can_administer: boolean;
            readonly drill_rollup?: components["schemas"]["DrillRollup"] | null;
        };
        /** TurnOut */
        readonly TurnOut: {
            /**
             * Id
             * Format: uuid
             */
            readonly id: string;
            /** Agent Slug */
            readonly agent_slug: string | null;
            /** Project */
            readonly project: string;
            /** Target */
            readonly target: string;
            /** Workspace Slug */
            readonly workspace_slug: string | null;
            /** Origin */
            readonly origin: string;
            /** Status */
            readonly status: string;
            /** Routing */
            readonly routing: string;
            /** Prompt */
            readonly prompt: string;
            /** Origin Ref */
            readonly origin_ref: {
                readonly [key: string]: unknown;
            };
            /** Claimed By Name */
            readonly claimed_by_name: string | null;
            /** Enqueued By Email */
            readonly enqueued_by_email: string | null;
            /** Session Id */
            readonly session_id: string;
            /** Result Note */
            readonly result_note: string;
            /**
             * Created At
             * Format: date-time
             */
            readonly created_at: string;
            /** Claimed At */
            readonly claimed_at: string | null;
            /** Started At */
            readonly started_at: string | null;
            /** Finished At */
            readonly finished_at: string | null;
            /** Lease Expires At */
            readonly lease_expires_at: string | null;
        };
        /** EmdashSessionOut */
        readonly EmdashSessionOut: {
            /**
             * Id
             * Format: uuid
             */
            readonly id: string;
            /** Emdash Task */
            readonly emdash_task: string;
            /** Project */
            readonly project: string;
            /** Agent */
            readonly agent: string | null;
            /** Status */
            readonly status: string;
            /** Last Interacted At */
            readonly last_interacted_at: string | null;
            /** Recent Messages */
            readonly recent_messages: readonly unknown[];
            /** Workspace */
            readonly workspace: string;
            /** Runner Name */
            readonly runner_name: string;
        };
        /** TurnEventOut */
        readonly TurnEventOut: {
            /** Seq */
            readonly seq: number;
            /**
             * Ts
             * Format: date-time
             */
            readonly ts: string;
            /** Kind */
            readonly kind: string;
            /** Payload */
            readonly payload: {
                readonly [key: string]: unknown;
            };
        };
        /** TurnEventsOut */
        readonly TurnEventsOut: {
            /** Events */
            readonly events: readonly components["schemas"]["TurnEventOut"][];
        };
        /** SessionOut */
        readonly SessionOut: {
            /**
             * Backfill Pending
             * @default false
             */
            readonly backfill_pending: boolean;
            /**
             * Id
             * Format: uuid
             */
            readonly id: string;
            /** Agent Slug */
            readonly agent_slug: string | null;
            /** Project */
            readonly project: string;
            /** Workspace */
            readonly workspace: string;
            /** Title */
            readonly title: string;
            /** Status */
            readonly status: string;
            /**
             * Created At
             * Format: date-time
             */
            readonly created_at: string;
            /**
             * Last Activity At
             * Format: date-time
             */
            readonly last_activity_at: string;
            /**
             * Origin
             * @default web
             */
            readonly origin: string;
            /**
             * Running
             * @default false
             */
            readonly running: boolean;
            /** Runner Name */
            readonly runner_name?: string | null;
            /** Runner Location */
            readonly runner_location?: string | null;
            /** Runner Online */
            readonly runner_online?: boolean | null;
            /** Runner Status */
            readonly runner_status?: string | null;
            /**
             * Session Key
             * @default
             */
            readonly session_key: string;
            /**
             * Waiting On You
             * @default false
             */
            readonly waiting_on_you: boolean;
        };
        /** MessageOut */
        readonly MessageOut: {
            /** Turn Index */
            readonly turn_index: number;
            /** Role */
            readonly role: string;
            /** Plaintext */
            readonly plaintext: string;
            /** Content */
            readonly content: {
                readonly [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            readonly created_at: string;
        };
        /**
         * MessagePageOut
         * @description One backward page of transcript for scroll-back ("Load earlier").
         */
        readonly MessagePageOut: {
            /** Messages */
            readonly messages: readonly components["schemas"]["MessageOut"][];
            /** Has More Before */
            readonly has_more_before: boolean;
        };
        /**
         * TurnOutMinimal
         * @description Just enough of a Turn for the /place response — the caller only needs to
         *     confirm the pin took, not the full harness TurnOut shape.
         */
        readonly TurnOutMinimal: {
            /**
             * Id
             * Format: uuid
             */
            readonly id: string;
            /** Status */
            readonly status: string;
            /** Pinned Runner Id */
            readonly pinned_runner_id?: string | null;
        };
        /**
         * PlaceIn
         * @description Body for POST /{session_id}/place — the chat banner's after-the-fact
         *     directed-placement decision on an already-queued turn.
         */
        readonly PlaceIn: {
            /** Placement */
            readonly placement: string;
        };
        /**
         * StreamStateOut
         * @description Whether the bound runner is being asked to stream this session live.
         */
        readonly StreamStateOut: {
            /** Streaming */
            readonly streaming: boolean;
        };
        /**
         * PageStateOut
         * @description The stored view, with the server-assigned `version` folded in.
         *
         *     An empty `state` means no page is attached OR the page declares nothing.
         *     Those are the same to a reader and deliberately so; neither is "the screen
         *     is blank".
         */
        readonly PageStateOut: {
            /**
             * State
             * @default {}
             */
            readonly state: {
                readonly [key: string]: unknown;
            };
            /**
             * Version
             * @default 0
             */
            readonly version: number;
        };
        /**
         * PageStateIn
         * @description What the attached page currently shows.
         *
         *     Replaces any previous declaration wholesale. Bounded on the server: a page
         *     that sends the rows it displays rather than the selection of them is
         *     refused, because the agent re-reads those rows itself under the caller's own
         *     permissions.
         */
        readonly PageStateIn: {
            /**
             * State
             * @default {}
             */
            readonly state: {
                readonly [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly apps_canopy_sessions_api_list_sessions: {
        readonly parameters: {
            readonly query?: {
                readonly state?: string;
                readonly limit?: number;
                readonly source?: string;
                readonly opp_slug?: string;
                readonly opp_run_id?: string;
                readonly origin_key?: string;
                readonly embed_app?: string;
                readonly resource?: string;
                readonly page_path?: string;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["SessionOut"][];
                };
            };
        };
    };
    readonly apps_canopy_sessions_api_get_session: {
        readonly parameters: {
            readonly query?: {
                readonly full?: boolean;
            };
            readonly header?: never;
            readonly path: {
                readonly session_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SessionDetailOut"];
                };
            };
        };
    };
    readonly apps_canopy_sessions_api_list_messages: {
        readonly parameters: {
            readonly query: {
                readonly before: number;
                readonly limit?: number;
            };
            readonly header?: never;
            readonly path: {
                readonly session_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["MessagePageOut"];
                };
            };
        };
    };
    readonly apps_canopy_sessions_api_attach_session: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly session_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["StreamStateOut"];
                };
            };
        };
    };
    readonly apps_canopy_sessions_api_detach_session: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly session_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["StreamStateOut"];
                };
            };
        };
    };
    readonly apps_canopy_sessions_api_place: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly session_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["PlaceIn"];
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TurnOutMinimal"];
                };
            };
        };
    };
    readonly apps_canopy_sessions_api_declare_page_state: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly session_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["PageStateIn"];
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["PageStateOut"];
                };
            };
        };
    };
    readonly apps_harness_api_list_runners: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["RunnerOut"][];
                };
            };
        };
    };
    readonly apps_harness_api_list_sessions: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["EmdashSessionOut"][];
                };
            };
        };
    };
    readonly apps_harness_api_list_turns: {
        readonly parameters: {
            readonly query?: {
                readonly agent?: string | null;
                readonly status?: string | null;
                readonly limit?: number;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["TurnOut"][];
                };
            };
        };
    };
    readonly apps_harness_api_read_turn_events: {
        readonly parameters: {
            readonly query?: {
                readonly after?: number;
            };
            readonly header?: never;
            readonly path: {
                readonly turn_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TurnEventsOut"];
                };
            };
        };
    };
}
