/**
 * Client for the workspace-scoped Videos API (apps/videos/api_v2.py).
 *
 * Uses raw fetch — the openapi-fetch typed client at client.v2.ts
 * depends on generated.ts, which is regenerated by CI on push. Until
 * that catches up, this module declares its own response types and
 * speaks the v2 bare-response shape (no envelope) directly.
 */

const API_PREFIX = (import.meta.env.BASE_URL ?? "/").replace(/\/$/, "");

function getCsrfToken(): string {
  if (typeof document === "undefined") return "";
  for (const raw of document.cookie.split(";")) {
    const [name, ...rest] = raw.trim().split("=");
    if (name === "csrftoken_ace" || name === "csrftoken") {
      return decodeURIComponent(rest.join("="));
    }
  }
  return "";
}

const UNSAFE = new Set(["POST", "PUT", "PATCH", "DELETE"]);

async function v2Fetch<T>(path: string, init: RequestInit = {}): Promise<T> {
  const method = (init.method ?? "GET").toUpperCase();
  const headers = new Headers(init.headers ?? {});
  if (!headers.has("Accept")) headers.set("Accept", "application/json");
  if (UNSAFE.has(method)) {
    const token = getCsrfToken();
    if (token && !headers.has("X-CSRFToken")) headers.set("X-CSRFToken", token);
    if (!headers.has("Content-Type") && init.body) {
      headers.set("Content-Type", "application/json");
    }
  }
  const resp = await fetch(API_PREFIX + path, { ...init, headers, credentials: "include" });
  if (!resp.ok) {
    let detail = `${resp.status} ${resp.statusText}`;
    try {
      const body = await resp.json();
      if (body?.detail) detail = body.detail;
      else if (body?.title) detail = body.title;
    } catch {
      /* not JSON */
    }
    throw new Error(detail);
  }
  if (resp.status === 204) return undefined as T;
  return (await resp.json()) as T;
}

export interface VideoProgramCard {
  slug: string;
  name: string;
  tagline: string | null;
  country_focus: string | null;
  status: string | null;
  program_url: string | null;
  manifest_count: number;
  has_explorer_build: boolean;
}

export interface VideoProgramDetail extends VideoProgramCard {
  explorer_url: string;
  yaml_path: string;
}

export interface RenderStatus {
  program_slug: string;
  busy: boolean;
  started_at: string | null;
}

const base = (workspaceSlug: string) => `/api/w/${workspaceSlug}/videos`;

export function listVideoPrograms(workspaceSlug: string): Promise<VideoProgramCard[]> {
  return v2Fetch<VideoProgramCard[]>(`${base(workspaceSlug)}/programs`);
}

export function getVideoProgram(
  workspaceSlug: string,
  programSlug: string,
): Promise<VideoProgramDetail> {
  return v2Fetch<VideoProgramDetail>(`${base(workspaceSlug)}/programs/${programSlug}`);
}

export function getRenderStatus(
  workspaceSlug: string,
  programSlug: string,
): Promise<RenderStatus> {
  return v2Fetch<RenderStatus>(`${base(workspaceSlug)}/programs/${programSlug}/render-status`);
}

export interface BuildResult {
  ok: boolean;
  triggered: boolean;
  mode: "render" | "build-only";
  message: string;
}

export function triggerBuild(
  workspaceSlug: string,
  programSlug: string,
  mode: "render" | "build-only" = "render",
): Promise<BuildResult> {
  return v2Fetch<BuildResult>(`${base(workspaceSlug)}/programs/${programSlug}/build`, {
    method: "POST",
    body: JSON.stringify({ mode }),
  });
}
