# Generated by Django 5.2.13 on 2026-05-15 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ace_workspaces', '0002_seed_dimagi_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioLibraryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=32)),
                ('drive_id', models.CharField(db_index=True, max_length=128)),
                ('voice_id', models.CharField(blank=True, max_length=128)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('text', models.TextField(blank=True)),
                ('duration_sec', models.FloatField(blank=True, null=True)),
                ('generated_at', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('ok', 'ok'), ('missing-sidecar', 'missing-sidecar'), ('missing-media', 'missing-media'), ('malformed-sidecar', 'malformed-sidecar')], default='ok', max_length=32)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_library_entries', to='ace_workspaces.workspace')),
            ],
            options={
                'ordering': ['-generated_at', 'hash'],
                'unique_together': {('workspace', 'hash')},
            },
        ),
        migrations.CreateModel(
            name='VideoLibraryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subfolder', models.CharField(max_length=128)),
                ('filename', models.CharField(max_length=256)),
                ('drive_id', models.CharField(db_index=True, max_length=128)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('ok', 'ok'), ('missing-sidecar', 'missing-sidecar'), ('missing-media', 'missing-media'), ('malformed-sidecar', 'malformed-sidecar')], default='ok', max_length=32)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_library_entries', to='ace_workspaces.workspace')),
            ],
            options={
                'ordering': ['subfolder', 'filename'],
                'unique_together': {('workspace', 'subfolder', 'filename')},
            },
        ),
    ]
