# Generated by Django 5.2.13 on 2026-06-17 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_workspaces', '0004_seed_dimagi_team_auto_join'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet_key', models.CharField(max_length=256)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('narration_sentence', models.TextField(blank=True)),
                ('in_seconds', models.FloatField()),
                ('out_seconds', models.FloatField()),
                ('duration_seconds', models.FloatField()),
                ('tags', models.JSONField(default=list)),
                ('provenance', models.CharField(blank=True, max_length=128, null=True)),
                ('source_run', models.CharField(blank=True, max_length=256)),
                ('narrative_slug', models.CharField(blank=True, max_length=256)),
                ('scene_index', models.IntegerField(blank=True, null=True)),
                ('source_clip_ref', models.CharField(blank=True, max_length=512)),
                ('source_clip_url', models.URLField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('ok', 'ok'), ('missing-sidecar', 'missing-sidecar'), ('missing-media', 'missing-media'), ('malformed-sidecar', 'malformed-sidecar')], default='ok', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snippets', to='videos.videolibraryentry')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_snippets', to='ace_workspaces.workspace')),
            ],
            options={
                'ordering': ['source_run', 'scene_index', 'snippet_key'],
                'unique_together': {('workspace', 'snippet_key')},
            },
        ),
    ]
