# Generated by Django 5.2.13 on 2026-05-15 16:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ace_workspaces', '0002_seed_dimagi_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackInstallation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slack_team_id', models.CharField(max_length=32, unique=True)),
                ('slack_team_name', models.CharField(max_length=255)),
                ('bot_user_id', models.CharField(max_length=32)),
                ('bot_token_encrypted', models.TextField()),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('ace_workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slack_installations', to='ace_workspaces.workspace')),
                ('installed_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slack_installations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'slack_installations',
            },
        ),
        migrations.CreateModel(
            name='SlackRunThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_id', models.CharField(max_length=32)),
                ('parent_ts', models.CharField(max_length=32)),
                ('opp_slug', models.CharField(max_length=255)),
                ('run_id', models.CharField(max_length=64)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('phase_messages', models.JSONField(default=dict)),
                ('parent_state_hash', models.CharField(blank=True, default='', max_length=64)),
                ('broken_at', models.DateTimeField(blank=True, null=True)),
                ('ace_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slack_run_threads', to=settings.AUTH_USER_MODEL)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_threads', to='ace_slack.slackinstallation')),
            ],
            options={
                'db_table': 'slack_run_threads',
                'indexes': [models.Index(fields=['ace_user', '-triggered_at'], name='slack_run_t_ace_use_2d431c_idx')],
                'constraints': [models.UniqueConstraint(fields=('opp_slug', 'run_id'), name='uniq_slack_run_thread_per_run')],
            },
        ),
        migrations.CreateModel(
            name='SlackUserLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slack_user_id', models.CharField(max_length=32)),
                ('slack_email', models.EmailField(blank=True, max_length=254)),
                ('slack_real_name', models.CharField(blank=True, max_length=255)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('unlinked_at', models.DateTimeField(blank=True, null=True)),
                ('ace_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_user_links', to=settings.AUTH_USER_MODEL)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='ace_slack.slackinstallation')),
            ],
            options={
                'db_table': 'slack_user_links',
                'constraints': [models.UniqueConstraint(condition=models.Q(('unlinked_at__isnull', True)), fields=('installation', 'slack_user_id'), name='uniq_slack_user_per_installation')],
            },
        ),
    ]
