# Generated by Django 5.2.13 on 2026-04-19 11:06

import django.db.models.deletion
import django_cryptography.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_system_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blob_encrypted', django_cryptography.fields.encrypt(models.TextField())),
                ('token_prefix', models.CharField(max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('last_validation_ok', models.BooleanField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cli_credential', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'common_user_credential',
            },
        ),
    ]
