/**
 * Real `GET …/lineage` payloads for spark/spark-facilitator/20261001-2208 (a
 * clone of dimagi-team's run, itself forked twice), built by the backend from
 * the real decisions.yaml files on 2026-10-04 and trimmed to six decisions.
 * Regenerate rather than hand-edit.
 */
import type { DecisionLineage } from "@/api/lineage";

export const MEMBER_LINEAGE: DecisionLineage = {
  "schema_version": 1,
  "scope": "lineage",
  "chain": [
    {
      "position": 0,
      "via": "cloned",
      "at_phase": "",
      "stage": "",
      "date": "2026-10-01",
      "readable": true,
      "workbench_url": "/ace/w/spark/opps/spark-facilitator/runs/20261001-2208",
      "summary_url": "/ace/opps/spark/spark-facilitator/runs/20261001-2208/summary",
      "workspace": "spark",
      "opp": "spark-facilitator",
      "run_id": "20261001-2208",
      "decisions": 198
    },
    {
      "position": 1,
      "via": "seeded",
      "at_phase": "commcare-setup",
      "stage": "app build",
      "date": "2026-10-01",
      "readable": true,
      "workbench_url": null,
      "summary_url": null,
      "workspace": "dimagi-team",
      "opp": "spark-facilitator",
      "run_id": "20261001-2208",
      "decisions": 170
    },
    {
      "position": 2,
      "via": "forked",
      "at_phase": "synthetic-data-and-workflows",
      "stage": "demo",
      "date": "2026-09-26",
      "readable": true,
      "workbench_url": null,
      "summary_url": null,
      "workspace": "dimagi-team",
      "opp": "spark-facilitator",
      "run_id": "20260926-1800",
      "decisions": 117
    },
    {
      "position": 3,
      "via": "",
      "at_phase": "",
      "stage": "",
      "date": "2026-09-25",
      "readable": true,
      "workbench_url": null,
      "summary_url": null,
      "workspace": "dimagi-team",
      "opp": "spark-facilitator",
      "run_id": "20260925-1536",
      "decisions": 117
    }
  ],
  "origins": {
    "working-language": {
      "kind": "carried",
      "from_position": 3,
      "from_run": "20260925-1536",
      "from_date": "2026-09-25",
      "previous_value": "",
      "by": "",
      "at": ""
    },
    "learn-latitude-starting-quiz": {
      "kind": "reaffirmed",
      "from_position": 1,
      "from_run": "20261001-2208",
      "from_date": "2026-10-01",
      "previous_value": "",
      "by": "",
      "at": ""
    },
    "sol-devices-and-system-of-record-2208": {
      "kind": "human",
      "from_position": null,
      "from_run": "",
      "from_date": "",
      "previous_value": "",
      "by": "",
      "at": ""
    },
    "program-reuse-vs-create-spark": {
      "kind": "changed",
      "from_position": 1,
      "from_run": "20261001-2208",
      "from_date": "2026-10-01",
      "previous_value": "Reuse e7ca0792 (MWK)",
      "by": "",
      "at": ""
    },
    "connect-latitude-payment-amount-spark": {
      "kind": "reaffirmed",
      "from_position": 3,
      "from_run": "20260925-1536",
      "from_date": "2026-09-25",
      "previous_value": "",
      "by": "",
      "at": ""
    },
    "open-question-recording-path-whole-community-group-declines": {
      "kind": "new",
      "from_position": null,
      "from_run": "",
      "from_date": "",
      "previous_value": "",
      "by": "",
      "at": ""
    }
  },
  "counts": {
    "new": 1,
    "carried": 76,
    "changed": 2,
    "reaffirmed": 38,
    "human": 1
  },
  "histories": {
    "working-language": [
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20260925-1536",
        "date": "2026-09-25",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "working-language",
        "match": "id",
        "value": "English source plus Chichewa (nya) and Tumbuka (tum)",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "Matches Spark's own app. Translations are ACE-authored and needs-review; native review is a downstream obligation.",
        "linked": false
      },
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20260926-1800",
        "date": "2026-09-26",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "working-language",
        "match": "id",
        "value": "English source plus Chichewa (nya) and Tumbuka (tum)",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "Matches Spark's own app. Translations are ACE-authored and needs-review; native review is a downstream obligation.",
        "linked": false
      },
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20261001-2208",
        "date": "2026-10-01",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "working-language",
        "match": "id",
        "value": "English source plus Chichewa (nya) and Tumbuka (tum)",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "Matches Spark's own app. Translations are ACE-authored and needs-review; native review is a downstream obligation.",
        "linked": false
      },
      {
        "workspace": "spark",
        "opp": "spark-facilitator",
        "run_id": "20261001-2208",
        "date": "2026-10-01",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "working-language",
        "match": "id",
        "value": "English source plus Chichewa (nya) and Tumbuka (tum)",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "Matches Spark's own app. Translations are ACE-authored and needs-review; native review is a downstream obligation.",
        "linked": true
      }
    ],
    "learn-latitude-starting-quiz": [
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20260925-1536",
        "date": "2026-09-25",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "learn-latitude-baseline-pretest",
        "match": "id",
        "value": "6-item non-gating pre-test added",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "ACE's assessment-gate standard wants a baseline distinct from the gate; it carries learn_module only, never connect.assessment, so it cannot unlock Deliver. Spo",
        "linked": false
      },
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20260926-1800",
        "date": "2026-09-26",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "learn-latitude-baseline-pretest",
        "match": "earlier-id",
        "value": "6-item non-gating pre-test added",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "ACE's assessment-gate standard wants a baseline distinct from the gate; it carries learn_module only, never connect.assessment, so it cannot unlock Deliver. Spo",
        "linked": false
      },
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20261001-2208",
        "date": "2026-10-01",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "learn-latitude-starting-quiz",
        "match": "id",
        "value": "6-item non-gating starting quiz",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "ACE's assessment-gate standard requires a baseline bank distinct from the gate; it carries learn_module only, never connect.assessment (ace#1131). Spot-check: L",
        "linked": false
      },
      {
        "workspace": "spark",
        "opp": "spark-facilitator",
        "run_id": "20261001-2208",
        "date": "2026-10-01",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "learn-latitude-starting-quiz",
        "match": "id",
        "value": "6-item non-gating starting quiz",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "ACE's assessment-gate standard requires a baseline bank distinct from the gate; it carries learn_module only, never connect.assessment (ace#1131). Spot-check: L",
        "linked": true
      }
    ],
    "sol-devices-and-system-of-record-2208": [
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20260925-1536",
        "date": "2026-09-25",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "solicitation-all-in-rate-and-devices",
        "match": "id",
        "value": "All-in, devices inside the rate",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "Standing operator directive (2026-09-08) requires an all-in per-verified-unit rate with no separately-funded line and an explicit worker-vs-organisation split (",
        "linked": false
      },
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20260926-1800",
        "date": "2026-09-26",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "solicitation-all-in-rate-and-devices",
        "match": "earlier-id",
        "value": "All-in, devices inside the rate",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "Standing operator directive (2026-09-08) requires an all-in per-verified-unit rate with no separately-funded line and an explicit worker-vs-organisation split (",
        "linked": false
      },
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20261001-2208",
        "date": "2026-10-01",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "sol-devices-and-system-of-record-2208",
        "match": "id",
        "value": "Not asked; rate all-in with CBF vs organisation split",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "Standing operator directives: devices, data and system of record are ASSUMED, never asked (2026-09-26), and the rate is ALL-IN with an explicit worker vs commod",
        "linked": false
      },
      {
        "workspace": "spark",
        "opp": "spark-facilitator",
        "run_id": "20261001-2208",
        "date": "2026-10-01",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "sol-devices-and-system-of-record-2208",
        "match": "id",
        "value": "Ask about devices; devices costed separately",
        "plain_value": "",
        "status": "overridden",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "Operator decision 2026-10-04 (Jonathan Jackson): we want to understand what each applicant will do about devices. The listing now asks how many CBFs already hav",
        "linked": true
      }
    ],
    "program-reuse-vs-create-spark": [
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20260925-1536",
        "date": "2026-09-25",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "program-reuse-vs-create",
        "match": "id",
        "value": "Create",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "Only domain+archetype match was a115e4f2, whose currency (USD) diverges from the PDD's MWK; the operator chose replacement. Spot-check: opp.yaml connect.program",
        "linked": false
      },
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20260926-1800",
        "date": "2026-09-26",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "program-reuse-vs-create",
        "match": "earlier-id",
        "value": "Create",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "Only domain+archetype match was a115e4f2, whose currency (USD) diverges from the PDD's MWK; the operator chose replacement. Spot-check: opp.yaml connect.program",
        "linked": false
      },
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20261001-2208",
        "date": "2026-10-01",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "program-reuse-vs-create-2208",
        "match": "earlier-id",
        "value": "Reuse e7ca0792 (MWK)",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "Unfiltered scan of ace-pm-org: 2 programs; e7ca0792 matches delivery type ace + longitudinal design, MWK/MWI per PDD §14; the other is a throwaway PM→NM probe. ",
        "linked": false
      },
      {
        "workspace": "spark",
        "opp": "spark-facilitator",
        "run_id": "20261001-2208",
        "date": "2026-10-01",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "program-reuse-vs-create-spark",
        "match": "id",
        "value": "Create",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "Unfiltered scan of spark-pm-org-test: 0 programs. The clone cleared opp.yaml.connect so the copy gets its own program in Spark's PM org; the source program live",
        "linked": true
      }
    ],
    "connect-latitude-payment-amount-spark": [
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20260925-1536",
        "date": "2026-09-25",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "connect-latitude-payment-amount",
        "match": "id",
        "value": "7500",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "Band midpoint, the figure PDD §10.1 uses for per-CBF earnings; replaced by the awarded rate. Spot-check: Connect › payment unit › amount.",
        "linked": false
      },
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20260926-1800",
        "date": "2026-09-26",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "connect-latitude-payment-amount",
        "match": "earlier-id",
        "value": "7500",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "Band midpoint, the figure PDD §10.1 uses for per-CBF earnings; replaced by the awarded rate. Spot-check: Connect › payment unit › amount.",
        "linked": false
      },
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20261001-2208",
        "date": "2026-10-01",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "connect-latitude-payment-amount-2208",
        "match": "earlier-id",
        "value": "7500",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "Band midpoint, the figure PDD §10.1 uses for per-CBF earnings; replaced by the awarded rate. Spot-check: Connect › payment unit › amount.",
        "linked": false
      },
      {
        "workspace": "spark",
        "opp": "spark-facilitator",
        "run_id": "20261001-2208",
        "date": "2026-10-01",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "connect-latitude-payment-amount-spark",
        "match": "id",
        "value": "7500",
        "plain_value": "7,500 MWK",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "Band midpoint, the figure PDD §10.1 uses for per-CBF earnings; replaced by the awarded rate. Spot-check: Connect › payment unit › amount.",
        "linked": true
      }
    ],
    "open-question-recording-path-whole-community-group-declines": [
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20260925-1536",
        "date": "2026-09-25",
        "in_lineage": true,
        "readable": true,
        "found": false,
        "by": "",
        "linked": false
      },
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20260926-1800",
        "date": "2026-09-26",
        "in_lineage": true,
        "readable": true,
        "found": false,
        "by": "",
        "linked": false
      },
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20261001-2208",
        "date": "2026-10-01",
        "in_lineage": true,
        "readable": true,
        "found": false,
        "by": "",
        "linked": false
      },
      {
        "workspace": "spark",
        "opp": "spark-facilitator",
        "run_id": "20261001-2208",
        "date": "2026-10-01",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "open-question-recording-path-whole-community-group-declines",
        "match": "id",
        "value": "Not decided — built as described",
        "plain_value": "No way to record it yet — the meeting goes unpaid",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "",
        "linked": true
      }
    ]
  },
  "viewer": {
    "is_member": true
  }
};

export const OUTSIDER_LINEAGE: DecisionLineage = {
  "schema_version": 1,
  "scope": "lineage",
  "chain": [
    {
      "position": 0,
      "via": "cloned",
      "at_phase": "",
      "stage": "",
      "date": "2026-10-01",
      "readable": true,
      "workbench_url": null,
      "summary_url": null,
      "workspace": null,
      "opp": null,
      "run_id": null,
      "decisions": null
    },
    {
      "position": 1,
      "via": "seeded",
      "at_phase": "",
      "stage": "app build",
      "date": "2026-10-01",
      "readable": true,
      "workbench_url": null,
      "summary_url": null,
      "workspace": null,
      "opp": null,
      "run_id": null,
      "decisions": null
    },
    {
      "position": 2,
      "via": "forked",
      "at_phase": "",
      "stage": "demo",
      "date": "2026-09-26",
      "readable": true,
      "workbench_url": null,
      "summary_url": null,
      "workspace": null,
      "opp": null,
      "run_id": null,
      "decisions": null
    },
    {
      "position": 3,
      "via": "",
      "at_phase": "",
      "stage": "",
      "date": "2026-09-25",
      "readable": true,
      "workbench_url": null,
      "summary_url": null,
      "workspace": null,
      "opp": null,
      "run_id": null,
      "decisions": null
    }
  ],
  "origins": {
    "working-language": {
      "kind": "carried",
      "from_position": 3,
      "from_run": null,
      "from_date": "2026-09-25",
      "previous_value": "",
      "by": "",
      "at": ""
    },
    "learn-latitude-starting-quiz": {
      "kind": "reaffirmed",
      "from_position": 1,
      "from_run": null,
      "from_date": "2026-10-01",
      "previous_value": "",
      "by": "",
      "at": ""
    },
    "sol-devices-and-system-of-record-2208": {
      "kind": "human",
      "from_position": null,
      "from_run": null,
      "from_date": "",
      "previous_value": "",
      "by": "",
      "at": ""
    },
    "program-reuse-vs-create-spark": {
      "kind": "changed",
      "from_position": 1,
      "from_run": null,
      "from_date": "2026-10-01",
      "previous_value": "",
      "by": "",
      "at": ""
    },
    "connect-latitude-payment-amount-spark": {
      "kind": "reaffirmed",
      "from_position": 3,
      "from_run": null,
      "from_date": "2026-09-25",
      "previous_value": "",
      "by": "",
      "at": ""
    },
    "open-question-recording-path-whole-community-group-declines": {
      "kind": "new",
      "from_position": null,
      "from_run": null,
      "from_date": "",
      "previous_value": "",
      "by": "",
      "at": ""
    }
  },
  "counts": {
    "new": 1,
    "carried": 76,
    "changed": 2,
    "reaffirmed": 38,
    "human": 1
  },
  "histories": {},
  "viewer": {
    "is_member": false
  }
};
