/**
 * Real `GET …/lineage` payloads for spark/spark-facilitator/20261001-2208 (a
 * clone of dimagi-team's run, itself forked twice), built by the backend from
 * the trimmed real decisions.yaml files in `apps/opps/tests/fixtures/lineage/`
 * and trimmed to six decisions. Regenerate rather than hand-edit:
 * `scripts/regen_lineage_fixtures.py`.
 */
import type { DecisionLineage } from "@/api/lineage";

export const MEMBER_LINEAGE: DecisionLineage = {
  "schema_version": 1,
  "scope": "lineage",
  "chain": [
    {
      "position": 0,
      "via": "cloned",
      "at_phase": "",
      "stage": "",
      "date": "2026-10-01",
      "copied_date": "",
      "readable": true,
      "workbench_url": "/ace/w/spark/opps/spark-facilitator/runs/20261001-2208",
      "summary_url": "/ace/opps/spark/spark-facilitator/runs/20261001-2208/summary",
      "workspace": "spark",
      "opp": "spark-facilitator",
      "run_id": "20261001-2208",
      "decisions": 18
    },
    {
      "position": 1,
      "via": "seeded",
      "at_phase": "commcare-setup",
      "stage": "app build",
      "date": "2026-10-01",
      "copied_date": "",
      "readable": true,
      "workbench_url": null,
      "summary_url": null,
      "workspace": "dimagi-team",
      "opp": "spark-facilitator",
      "run_id": "20261001-2208",
      "decisions": 14
    },
    {
      "position": 2,
      "via": "forked",
      "at_phase": "synthetic-data-and-workflows",
      "stage": "demo",
      "date": "2026-09-26",
      "copied_date": "",
      "readable": true,
      "workbench_url": null,
      "summary_url": null,
      "workspace": "dimagi-team",
      "opp": "spark-facilitator",
      "run_id": "20260926-1800",
      "decisions": 8
    },
    {
      "position": 3,
      "via": "",
      "at_phase": "",
      "stage": "",
      "date": "2026-09-25",
      "copied_date": "",
      "readable": true,
      "workbench_url": null,
      "summary_url": null,
      "workspace": "dimagi-team",
      "opp": "spark-facilitator",
      "run_id": "20260925-1536",
      "decisions": 8
    }
  ],
  "origins": {
    "working-language": {
      "kind": "carried",
      "from_position": 3,
      "from_run": "20260925-1536",
      "from_date": "2026-09-25",
      "in_position": 1,
      "in_run": "20261001-2208",
      "in_date": "2026-10-01",
      "on_copy": false,
      "previous_value": "",
      "by": "",
      "at": ""
    },
    "learn-latitude-starting-quiz": {
      "kind": "changed",
      "from_position": 2,
      "from_run": "20260926-1800",
      "from_date": "2026-09-26",
      "in_position": 1,
      "in_run": "20261001-2208",
      "in_date": "2026-10-01",
      "on_copy": false,
      "previous_value": "6-item non-gating pre-test added",
      "by": "",
      "at": ""
    },
    "sol-devices-and-system-of-record-2208": {
      "kind": "human",
      "from_position": null,
      "from_run": "",
      "from_date": "",
      "in_position": null,
      "in_run": null,
      "in_date": "",
      "on_copy": false,
      "previous_value": "",
      "by": "",
      "at": ""
    },
    "program-reuse-vs-create-spark": {
      "kind": "changed",
      "from_position": 1,
      "from_run": "20261001-2208",
      "from_date": "2026-10-01",
      "in_position": 0,
      "in_run": "20261001-2208",
      "in_date": "2026-10-01",
      "on_copy": true,
      "previous_value": "Reuse e7ca0792 (MWK)",
      "by": "",
      "at": ""
    },
    "connect-latitude-payment-amount-spark": {
      "kind": "reaffirmed",
      "from_position": 3,
      "from_run": "20260925-1536",
      "from_date": "2026-09-25",
      "in_position": 1,
      "in_run": "20261001-2208",
      "in_date": "2026-10-01",
      "on_copy": false,
      "previous_value": "",
      "by": "",
      "at": ""
    },
    "open-question-recording-path-whole-community-group-declines": {
      "kind": "new",
      "from_position": null,
      "from_run": "",
      "from_date": "",
      "in_position": 0,
      "in_run": "20261001-2208",
      "in_date": "2026-10-01",
      "on_copy": false,
      "previous_value": "",
      "by": "",
      "at": ""
    }
  },
  "counts": {
    "new": 1,
    "decided": 0,
    "carried": 1,
    "changed": 4,
    "reaffirmed": 1,
    "human": 1
  },
  "histories": {
    "working-language": [
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20260925-1536",
        "date": "2026-09-25",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "working-language",
        "match": "id",
        "value": "English source plus Chichewa (nya) and Tumbuka (tum)",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "Matches Spark's own app. Translations are ACE-authored and needs-review; native review is a downstream obligation.",
        "linked": false
      },
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20260926-1800",
        "date": "2026-09-26",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "working-language",
        "match": "id",
        "value": "English source plus Chichewa (nya) and Tumbuka (tum)",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "Matches Spark's own app. Translations are ACE-authored and needs-review; native review is a downstream obligation.",
        "linked": false
      },
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20261001-2208",
        "date": "2026-10-01",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "working-language",
        "match": "id",
        "value": "English source plus Chichewa (nya) and Tumbuka (tum)",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "Matches Spark's own app. Translations are ACE-authored and needs-review; native review is a downstream obligation.",
        "copied_to": [
          {
            "workspace": "spark",
            "date": ""
          }
        ],
        "current": true,
        "linked": false
      }
    ],
    "learn-latitude-starting-quiz": [
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20260925-1536",
        "date": "2026-09-25",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "learn-latitude-baseline-pretest",
        "match": "id",
        "value": "6-item non-gating pre-test added",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "ACE's assessment-gate standard wants a baseline distinct from the gate; it carries learn_module only, never connect.assessment, so it cannot unlock Deliver. Spot-check: Learn app \u203a Before you start \u203a Starting quiz.",
        "linked": false
      },
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20260926-1800",
        "date": "2026-09-26",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "learn-latitude-baseline-pretest",
        "match": "earlier-id",
        "value": "6-item non-gating pre-test added",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "ACE's assessment-gate standard wants a baseline distinct from the gate; it carries learn_module only, never connect.assessment, so it cannot unlock Deliver. Spot-check: Learn app \u203a Before you start \u203a Starting quiz.",
        "linked": false
      },
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20261001-2208",
        "date": "2026-10-01",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "learn-latitude-starting-quiz",
        "match": "id",
        "value": "6-item non-gating starting quiz",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "ACE's assessment-gate standard requires a baseline bank distinct from the gate; it carries learn_module only, never connect.assessment (ace#1131). Spot-check: Learn app \u203a Before you start \u203a Starting quiz.",
        "copied_to": [
          {
            "workspace": "spark",
            "date": ""
          }
        ],
        "current": true,
        "linked": false
      }
    ],
    "sol-devices-and-system-of-record-2208": [
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20260925-1536",
        "date": "2026-09-25",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "solicitation-all-in-rate-and-devices",
        "match": "id",
        "value": "All-in, devices inside the rate",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "Standing operator directive (2026-09-08) requires an all-in per-verified-unit rate with no separately-funded line and an explicit worker-vs-organisation split (ace#2265). The PDD band (MWK 5,000-10,000 to the CBF + MWK 3,000 organisation floor, both PROPOSED; Phase 4 payment unit 7,500 + 3,000) is shown as an indicative all-in MWK 8,000-13,000. This deviates from work order \u00a72 / PDD \u00a712, which let the partner cost device provision separately; the listing instead asks how any device gap is carried inside the rate. The work order text should be reconciled at contract execution.",
        "linked": false
      },
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20260926-1800",
        "date": "2026-09-26",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "solicitation-all-in-rate-and-devices",
        "match": "earlier-id",
        "value": "All-in, devices inside the rate",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "Standing operator directive (2026-09-08) requires an all-in per-verified-unit rate with no separately-funded line and an explicit worker-vs-organisation split (ace#2265). The PDD band (MWK 5,000-10,000 to the CBF + MWK 3,000 organisation floor, both PROPOSED; Phase 4 payment unit 7,500 + 3,000) is shown as an indicative all-in MWK 8,000-13,000. This deviates from work order \u00a72 / PDD \u00a712, which let the partner cost device provision separately; the listing instead asks how any device gap is carried inside the rate. The work order text should be reconciled at contract execution.",
        "linked": false
      },
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20261001-2208",
        "date": "2026-10-01",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "sol-devices-and-system-of-record-2208",
        "match": "id",
        "value": "Not asked; rate all-in with CBF vs organisation split",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "Standing operator directives: devices, data and system of record are ASSUMED, never asked (2026-09-26), and the rate is ALL-IN with an explicit worker vs commodity split and no separately-funded line (2026-09-08, ace#2265). The PDD \u00a712 / work order \u00a72 device go/no-go and separately-costed device plan, and the instead-of/in-addition-to filing ask, are therefore omitted from the listing. Indicative all-in band shown as MWK 8,000-13,000 (CBF 5,000-10,000 + organisation 3,000, both PROPOSED). Work order \u00a72/\u00a76.1 text should be reconciled at contract execution.",
        "linked": false
      },
      {
        "workspace": "spark",
        "opp": "spark-facilitator",
        "run_id": "20261001-2208",
        "date": "2026-10-01",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "sol-devices-and-system-of-record-2208",
        "match": "id",
        "value": "Ask about devices; devices costed separately",
        "plain_value": "",
        "status": "overridden",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "Operator decision 2026-10-04 (Jonathan Jackson): we want to understand what each applicant will do about devices. The listing now asks how many CBFs already have a working smartphone and mobile data and, for the rest, a costed device plan stated separately from the per-meeting rate; Dimagi agrees that cost at contract execution. This overrides the 2026-09-26 'devices assumed, never asked' directive for this pilot only, because the PDD's own evidence (Spark's tablet-and-file-share programme) argues against assuming smartphones. The work order \u00a72/\u00a76.1 follows. Whether CBFs file instead of or in ",
        "current": true,
        "linked": true
      }
    ],
    "program-reuse-vs-create-spark": [
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20260925-1536",
        "date": "2026-09-25",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "program-reuse-vs-create",
        "match": "id",
        "value": "Create",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "Only domain+archetype match was a115e4f2, whose currency (USD) diverges from the PDD's MWK; the operator chose replacement. Spot-check: opp.yaml connect.program.id.",
        "linked": false
      },
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20260926-1800",
        "date": "2026-09-26",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "program-reuse-vs-create",
        "match": "earlier-id",
        "value": "Create",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "Only domain+archetype match was a115e4f2, whose currency (USD) diverges from the PDD's MWK; the operator chose replacement. Spot-check: opp.yaml connect.program.id.",
        "linked": false
      },
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20261001-2208",
        "date": "2026-10-01",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "program-reuse-vs-create-2208",
        "match": "earlier-id",
        "value": "Reuse e7ca0792 (MWK)",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "Unfiltered scan of ace-pm-org: 2 programs; e7ca0792 matches delivery type ace + longitudinal design, MWK/MWI per PDD \u00a714; the other is a throwaway PM\u2192NM probe. Description refreshed to keep 'instead of or in addition to Spark's form' open (PDD \u00a715). Budget ceiling 32,760,000 kept: \u03a3 3,276,000 over 1 opp, headroom ample. Spot-check: Connect \u203a program e7ca0792 \u203a description.",
        "linked": false
      },
      {
        "workspace": "spark",
        "opp": "spark-facilitator",
        "run_id": "20261001-2208",
        "date": "2026-10-01",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "program-reuse-vs-create-spark",
        "match": "id",
        "value": "Create",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "Unfiltered scan of spark-pm-org-test: 0 programs. The clone cleared opp.yaml.connect so the copy gets its own program in Spark's PM org; the source program lives in ace-pm-org, outside this tenancy. Created f537601b. Spot-check: opp.yaml connect.program.id.",
        "current": true,
        "linked": true
      }
    ],
    "connect-latitude-payment-amount-spark": [
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20260925-1536",
        "date": "2026-09-25",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "connect-latitude-payment-amount",
        "match": "id",
        "value": "7500",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "Band midpoint, the figure PDD \u00a710.1 uses for per-CBF earnings; replaced by the awarded rate. Spot-check: Connect \u203a payment unit \u203a amount.",
        "linked": false
      },
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20260926-1800",
        "date": "2026-09-26",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "connect-latitude-payment-amount",
        "match": "earlier-id",
        "value": "7500",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "Band midpoint, the figure PDD \u00a710.1 uses for per-CBF earnings; replaced by the awarded rate. Spot-check: Connect \u203a payment unit \u203a amount.",
        "linked": false
      },
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20261001-2208",
        "date": "2026-10-01",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "connect-latitude-payment-amount-2208",
        "match": "earlier-id",
        "value": "7500",
        "plain_value": "",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "Band midpoint, the figure PDD \u00a710.1 uses for per-CBF earnings; replaced by the awarded rate. Spot-check: Connect \u203a payment unit \u203a amount.",
        "copied_to": [
          {
            "workspace": "spark",
            "date": ""
          }
        ],
        "current": true,
        "linked": false
      }
    ],
    "open-question-recording-path-whole-community-group-declines": [
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20260925-1536",
        "date": "2026-09-25",
        "in_lineage": true,
        "readable": true,
        "found": false,
        "by": "",
        "linked": false
      },
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20260926-1800",
        "date": "2026-09-26",
        "in_lineage": true,
        "readable": true,
        "found": false,
        "by": "",
        "linked": false
      },
      {
        "workspace": "dimagi-team",
        "opp": "spark-facilitator",
        "run_id": "20261001-2208",
        "date": "2026-10-01",
        "in_lineage": true,
        "readable": true,
        "found": false,
        "by": "",
        "linked": false
      },
      {
        "workspace": "spark",
        "opp": "spark-facilitator",
        "run_id": "20261001-2208",
        "date": "2026-10-01",
        "in_lineage": true,
        "readable": true,
        "found": true,
        "row_id": "open-question-recording-path-whole-community-group-declines",
        "match": "id",
        "value": "Not decided \u2014 built as described",
        "plain_value": "No way to record it yet \u2014 the meeting goes unpaid",
        "status": "ai-default",
        "superseded": false,
        "by": "",
        "at": "",
        "reason": "",
        "current": true,
        "linked": true
      }
    ]
  },
  "viewer": {
    "is_member": true
  }
};
export const OUTSIDER_LINEAGE: DecisionLineage = {
  "schema_version": 1,
  "scope": "lineage",
  "chain": [
    {
      "position": 0,
      "via": "cloned",
      "at_phase": "",
      "stage": "",
      "date": "2026-10-01",
      "copied_date": "",
      "readable": true,
      "workbench_url": null,
      "summary_url": null,
      "workspace": null,
      "opp": null,
      "run_id": null,
      "decisions": null
    },
    {
      "position": 1,
      "via": "seeded",
      "at_phase": "",
      "stage": "app build",
      "date": "2026-10-01",
      "copied_date": "",
      "readable": true,
      "workbench_url": null,
      "summary_url": null,
      "workspace": null,
      "opp": null,
      "run_id": null,
      "decisions": null
    },
    {
      "position": 2,
      "via": "forked",
      "at_phase": "",
      "stage": "demo",
      "date": "2026-09-26",
      "copied_date": "",
      "readable": true,
      "workbench_url": null,
      "summary_url": null,
      "workspace": null,
      "opp": null,
      "run_id": null,
      "decisions": null
    },
    {
      "position": 3,
      "via": "",
      "at_phase": "",
      "stage": "",
      "date": "2026-09-25",
      "copied_date": "",
      "readable": true,
      "workbench_url": null,
      "summary_url": null,
      "workspace": null,
      "opp": null,
      "run_id": null,
      "decisions": null
    }
  ],
  "origins": {
    "working-language": {
      "kind": "carried",
      "from_position": 3,
      "from_run": null,
      "from_date": "2026-09-25",
      "in_position": 1,
      "in_run": null,
      "in_date": "2026-10-01",
      "on_copy": false,
      "previous_value": "",
      "by": "",
      "at": ""
    },
    "learn-latitude-starting-quiz": {
      "kind": "changed",
      "from_position": 2,
      "from_run": null,
      "from_date": "2026-09-26",
      "in_position": 1,
      "in_run": null,
      "in_date": "2026-10-01",
      "on_copy": false,
      "previous_value": "",
      "by": "",
      "at": ""
    },
    "sol-devices-and-system-of-record-2208": {
      "kind": "human",
      "from_position": null,
      "from_run": null,
      "from_date": "",
      "in_position": null,
      "in_run": null,
      "in_date": "",
      "on_copy": false,
      "previous_value": "",
      "by": "",
      "at": ""
    },
    "program-reuse-vs-create-spark": {
      "kind": "changed",
      "from_position": 1,
      "from_run": null,
      "from_date": "2026-10-01",
      "in_position": 0,
      "in_run": null,
      "in_date": "2026-10-01",
      "on_copy": true,
      "previous_value": "",
      "by": "",
      "at": ""
    },
    "connect-latitude-payment-amount-spark": {
      "kind": "reaffirmed",
      "from_position": 3,
      "from_run": null,
      "from_date": "2026-09-25",
      "in_position": 1,
      "in_run": null,
      "in_date": "2026-10-01",
      "on_copy": false,
      "previous_value": "",
      "by": "",
      "at": ""
    },
    "open-question-recording-path-whole-community-group-declines": {
      "kind": "new",
      "from_position": null,
      "from_run": null,
      "from_date": "",
      "in_position": 0,
      "in_run": null,
      "in_date": "2026-10-01",
      "on_copy": false,
      "previous_value": "",
      "by": "",
      "at": ""
    }
  },
  "counts": {
    "new": 1,
    "decided": 0,
    "carried": 1,
    "changed": 4,
    "reaffirmed": 1,
    "human": 1
  },
  "histories": {},
  "viewer": {
    "is_member": false
  }
};
