# Generated by Django 5.2.13 on 2026-04-10 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('credential_type', models.CharField(choices=[('google_sa', 'Google Service Account'), ('api_key', 'API Key')], max_length=50)),
                ('credential_encrypted', models.TextField()),
                ('default_scopes', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_accounts',
            },
        ),
        migrations.CreateModel(
            name='ImpersonationGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_pattern', models.CharField(max_length=200)),
                ('scopes', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='service_accounts.serviceaccount')),
            ],
            options={
                'db_table': 'impersonation_grants',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('subject', models.CharField(blank=True, default='', max_length=200)),
                ('scopes_used', models.JSONField(default=list)),
                ('context', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='service_accounts.serviceaccount')),
            ],
            options={
                'db_table': 'service_account_access_log',
                'indexes': [models.Index(fields=['service_account', '-created_at'], name='service_acc_service_a6a061_idx')],
            },
        ),
    ]
