# Generated by Django 5.2.13 on 2026-04-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='drive_token_cache',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='drive_token_refreshed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
