# Generated by Django 5.2.13 on 2026-04-09 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ace_auth', '0002_drive_token_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='drive_token_cache',
        ),
        migrations.RemoveField(
            model_name='user',
            name='drive_token_refreshed_at',
        ),
    ]
