# Generated by Django 5.2.13 on 2026-04-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ace_auth', '0003_drop_drive_token_fields'),
        ('ace_auth', '0003_personaltoken'),
    ]

    operations = [
    ]
