# Generated by Django 5.2.13 on 2026-09-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ace_auth", "0004_merge_0003_drop_drive_token_fields_0003_personaltoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="personaltoken",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
