# Generated by Django 5.2.13 on 2026-04-15 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OppWorkspace',
            fields=[
                ('slug', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_opps', to=settings.AUTH_USER_MODEL)),
                ('working_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opp_working_for', to='sessions.session')),
            ],
            options={
                'db_table': 'opp_workspaces',
                'indexes': [models.Index(fields=['-created_at'], name='opp_workspa_created_7e8ccf_idx')],
            },
        ),
    ]
