# Generated by Django 5.2.13 on 2026-04-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oppworkspace',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Free-form tags for grouping related opps (e.g. iterations of the same idea). Future UI: tag filter + side-by-side compare. See docs/plans/2026-04-20-drop-multi-run-simplify.md.'),
        ),
    ]
