# Generated by Django 5.2.13 on 2026-04-27 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_workspaces', '0001_initial'),
        ('opps', '0002_oppworkspace_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='oppworkspace',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opps', to='ace_workspaces.workspace'),
        ),
    ]
