# Generated by Django 5.2.17 on 2026-09-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opps", "0004_oppworkspace_workspace_required_and_pk_pivot"),
    ]

    operations = [
        migrations.AddField(
            model_name="oppworkspace",
            name="tenancy",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
