"""Django Ninja v2 router for the workspace-scoped Videos surface.

Mounted under ``/api/w/{workspace_slug}/videos`` from
``apps/api_v2/api.py``. Reads (and a couple of safe writes) are flagged
``x-mcp-expose: True`` so the FastMCP bridge can call them.

The clip-explorer HTML lives at ``out/clip-explorer/<slug>/index.html``
under ``ACE_VIDEOS_ROOT`` — generated by the Node project at
``video-production/connect-videos/``. Django serves it through this
router so the rest of ace-web's session auth + workspace gating apply.
"""
from __future__ import annotations

import logging
from typing import Annotated

from django.conf import settings
from django.http import FileResponse, HttpRequest, HttpResponse, StreamingHttpResponse
from ninja import Path as PathParam
from ninja import Router

from apps.api_v2.auth import session_auth
from apps.api_v2.deps import resolve_workspace_for_member
from apps.api_v2.errors import TYPE_NOT_FOUND, TYPE_VALIDATION, ProblemError

from . import service
from .schemas import (
    ClipEditIn,
    ClipEditOut,
    FeedbackLogOut,
    FeedbackPostIn,
    FeedbackPostOut,
    LibraryEntryOut,
    LibraryOut,
    ProgramCardOut,
    ProgramDetailOut,
    RenderStatusOut,
)

log = logging.getLogger(__name__)

router = Router(auth=session_auth, tags=["videos"])


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _require_program(workspace_slug: str, program_slug: str) -> service.ProgramRecord:
    """Resolve a program for a workspace member, 404ing on mismatch.

    Slug whitelist runs before any FS access so invalid slugs never reach
    ``programs/`` lookups or subprocess spawns.
    """
    if not service.is_valid_slug(program_slug):
        raise ProblemError(404, "Not found", type_=TYPE_NOT_FOUND)
    record = service.load_program(program_slug)
    if record is None or record.workspace_slug != workspace_slug:
        raise ProblemError(404, "Not found", type_=TYPE_NOT_FOUND)
    return record


def _explorer_url(workspace_slug: str, program_slug: str) -> str:
    return f"/api/w/{workspace_slug}/videos/programs/{program_slug}/explorer.html"


def _program_card(record: service.ProgramRecord) -> dict:
    return {
        "slug": record.slug,
        "name": record.name,
        "tagline": record.tagline,
        "country_focus": record.country_focus,
        "status": record.status,
        "program_url": record.program_url,
        "manifest_count": record.manifest_count,
        "has_explorer_build": record.has_explorer_build,
    }


# ---------------------------------------------------------------------------
# JSON: programs list / detail / library / render status / feedback
# ---------------------------------------------------------------------------


@router.get(
    "/programs",
    response=list[ProgramCardOut],
    summary="List video programs in workspace",
    openapi_extra={"x-mcp-expose": True},
)
def list_programs(
    request: HttpRequest,
    workspace_slug: Annotated[str, PathParam()],
) -> list[ProgramCardOut]:
    resolve_workspace_for_member(request, workspace_slug)
    return [
        ProgramCardOut.model_validate(_program_card(r))
        for r in service.list_programs_for_workspace(workspace_slug)
    ]


@router.get(
    "/programs/{program_slug}",
    response=ProgramDetailOut,
    summary="Get a video program's detail payload",
    openapi_extra={"x-mcp-expose": True},
)
def get_program(
    request: HttpRequest,
    workspace_slug: Annotated[str, PathParam()],
    program_slug: Annotated[str, PathParam()],
) -> ProgramDetailOut:
    resolve_workspace_for_member(request, workspace_slug)
    record = _require_program(workspace_slug, program_slug)
    payload = _program_card(record)
    payload["explorer_url"] = _explorer_url(workspace_slug, program_slug)
    # Display the YAML path relative to the parent of ACE_VIDEOS_ROOT
    # (i.e. the directory that contains video-production/). Anchored on
    # ACE_VIDEOS_ROOT rather than BASE_DIR so the path resolves cleanly
    # in tests, in dev, and in prod regardless of where the videos root
    # sits in the tree.
    from pathlib import Path as _Path
    yaml_root = _Path(settings.ACE_VIDEOS_ROOT).parent.parent
    try:
        payload["yaml_path"] = str(record.yaml_path.relative_to(yaml_root))
    except ValueError:
        payload["yaml_path"] = record.yaml_path.name

    return ProgramDetailOut.model_validate(payload)


@router.get(
    "/programs/{program_slug}/library.json",
    response=LibraryOut,
    summary="Structured clip library for the explorer drawer",
    openapi_extra={"x-mcp-expose": True},
)
def get_library(
    request: HttpRequest,
    workspace_slug: Annotated[str, PathParam()],
    program_slug: Annotated[str, PathParam()],
) -> LibraryOut:
    resolve_workspace_for_member(request, workspace_slug)
    _require_program(workspace_slug, program_slug)
    entries = [LibraryEntryOut.model_validate(e) for e in service.load_library_entries(program_slug)]
    return LibraryOut(entries=entries)


@router.get(
    "/programs/{program_slug}/render-status",
    response=RenderStatusOut,
    summary="Background-render busy flag for a program",
    openapi_extra={"x-mcp-expose": True},
)
def get_render_status(
    request: HttpRequest,
    workspace_slug: Annotated[str, PathParam()],
    program_slug: Annotated[str, PathParam()],
) -> RenderStatusOut:
    resolve_workspace_for_member(request, workspace_slug)
    _require_program(workspace_slug, program_slug)
    return RenderStatusOut.model_validate(service.render_status(program_slug))


@router.get(
    "/programs/{program_slug}/feedback",
    response=FeedbackLogOut,
    summary="Read the per-program feedback markdown log",
    openapi_extra={"x-mcp-expose": True},
)
def get_feedback(
    request: HttpRequest,
    workspace_slug: Annotated[str, PathParam()],
    program_slug: Annotated[str, PathParam()],
) -> FeedbackLogOut:
    resolve_workspace_for_member(request, workspace_slug)
    _require_program(workspace_slug, program_slug)
    path = service.feedback_path(program_slug)
    markdown = path.read_text(encoding="utf-8") if path.exists() else ""
    return FeedbackLogOut(program_slug=program_slug, markdown=markdown)


@router.post(
    "/programs/{program_slug}/feedback",
    response=FeedbackPostOut,
    summary="Append a note to the per-program feedback markdown log",
)
def post_feedback(
    request: HttpRequest,
    workspace_slug: Annotated[str, PathParam()],
    program_slug: Annotated[str, PathParam()],
    body: FeedbackPostIn,
) -> FeedbackPostOut:
    import datetime as dt

    resolve_workspace_for_member(request, workspace_slug)
    _require_program(workspace_slug, program_slug)
    ts = dt.datetime.now(dt.UTC).replace(microsecond=0).strftime("%Y-%m-%d %H:%M:%S")
    scope = f"beat:{body.beatId}" if body.scope == "beat" and body.beatId else "global"
    time_bit = f" (video t={body.timestampSec:.1f}s)" if body.timestampSec is not None else ""
    line = f"\n## [{ts}] {scope}{time_bit}\n\n{body.note}\n"
    path = service.feedback_path(program_slug)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as f:
        f.write(line)
    return FeedbackPostOut(ok=True, timestamp=ts)


@router.post(
    "/programs/{program_slug}/edit",
    response=ClipEditOut,
    summary="Mutate a clip / narration in the program YAML, fire a draft re-render",
)
def post_edit(
    request: HttpRequest,
    workspace_slug: Annotated[str, PathParam()],
    program_slug: Annotated[str, PathParam()],
    body: ClipEditIn,
) -> ClipEditOut:
    resolve_workspace_for_member(request, workspace_slug)
    _require_program(workspace_slug, program_slug)
    result = service.apply_edit(program_slug, body.model_dump(exclude_none=True))
    if not result.ok:
        raise ProblemError(
            400,
            "Edit could not be applied",
            type_=TYPE_VALIDATION,
            detail=result.message,
        )
    needs_hydrate = body.op == "set-clip-asset"
    rerender_triggered = service.trigger_rerender(program_slug, needs_hydrate=needs_hydrate)
    return ClipEditOut(
        ok=True,
        message=result.message + (
            " — re-render kicked off in background" if rerender_triggered
            else " — render already in flight; skipped duplicate"
        ),
        rerender_triggered=rerender_triggered,
    )


# ---------------------------------------------------------------------------
# HTML + static media (the iframe surface)
# ---------------------------------------------------------------------------


def _serve_rewritten_html(workspace_slug: str, program_slug: str, filename: str) -> HttpResponse:
    src = service.explorer_dir(program_slug) / filename
    if not src.exists():
        raise ProblemError(
            404,
            "Explorer build not found",
            type_=TYPE_NOT_FOUND,
            detail=(
                "Run `npm run build-clip-explorer -- --program=" + program_slug + "` "
                "from video-production/connect-videos/ to generate it."
            ),
        )
    prefix = f"/api/w/{workspace_slug}/videos/programs/{program_slug}/"
    csrf_cookie = getattr(settings, "CSRF_COOKIE_NAME", "csrftoken")
    html = service.rewrite_explorer_html(
        src.read_text(encoding="utf-8"),
        prefix=prefix,
        csrf_cookie_name=csrf_cookie,
    )
    response = HttpResponse(html, content_type="text/html; charset=utf-8")
    # Iframe-safe under the same origin; ace-web's clickjacking middleware
    # otherwise sets DENY. ``SAMEORIGIN`` lets the React shell embed it.
    response["X-Frame-Options"] = "SAMEORIGIN"
    return response


@router.get(
    "/programs/{program_slug}/explorer.html",
    summary="Serve the generated clip-explorer index.html (rewritten for iframe)",
)
def serve_explorer(
    request: HttpRequest,
    workspace_slug: Annotated[str, PathParam()],
    program_slug: Annotated[str, PathParam()],
) -> HttpResponse:
    resolve_workspace_for_member(request, workspace_slug)
    _require_program(workspace_slug, program_slug)
    return _serve_rewritten_html(workspace_slug, program_slug, "index.html")


@router.get(
    "/programs/{program_slug}/library.html",
    summary="Serve the generated clip-library.html (rewritten for iframe)",
)
def serve_library_html(
    request: HttpRequest,
    workspace_slug: Annotated[str, PathParam()],
    program_slug: Annotated[str, PathParam()],
) -> HttpResponse:
    resolve_workspace_for_member(request, workspace_slug)
    _require_program(workspace_slug, program_slug)
    return _serve_rewritten_html(workspace_slug, program_slug, "library.html")


@router.get(
    "/programs/{program_slug}/media/{file_name}",
    summary="Serve an MP4 from the program's explorer media directory (Range-aware)",
)
def serve_media(
    request: HttpRequest,
    workspace_slug: Annotated[str, PathParam()],
    program_slug: Annotated[str, PathParam()],
    file_name: Annotated[str, PathParam()],
) -> HttpResponse | StreamingHttpResponse:
    resolve_workspace_for_member(request, workspace_slug)
    _require_program(workspace_slug, program_slug)

    media_dir = service.explorer_dir(program_slug) / "media"
    try:
        target = (media_dir / file_name).resolve()
        # Reject path traversal: target must stay under media_dir (resolved).
        target.relative_to(media_dir.resolve())
    except (OSError, ValueError):
        raise ProblemError(404, "Not found", type_=TYPE_NOT_FOUND) from None
    if not target.is_file():
        raise ProblemError(404, "Not found", type_=TYPE_NOT_FOUND)

    # FileResponse handles Range-request streaming automatically when the
    # caller sends ``Range: bytes=…``; this is the same code path the
    # browser uses for video scrubbing.
    response = FileResponse(target.open("rb"), as_attachment=False)
    # Hint content type for common video mime — FileResponse guesses from
    # extension but be explicit.
    suffix = target.suffix.lower()
    if suffix in {".mp4", ".m4v"}:
        response["Content-Type"] = "video/mp4"
    elif suffix == ".webm":
        response["Content-Type"] = "video/webm"
    return response


