#!/bin/bash
# Bake one AVD snapshot per CommCare APK version. For each version V in
# COMMCARE_VERSIONS, this script:
#   1. boots the AVD fresh (no prior snapshot)
#   2. installs /opt/ace/apks/V/commcare.apk
#   3. runs the two +7426-demo registration recipes
#   4. `adb emu avd snapshot save cc-V-registered`
#   5. `sync` (so the AMI capture sees a consistent userdata-qemu.img)
#   6. `adb emu kill`
#
# After all versions complete, writes /opt/ace/states.yaml describing
# the available named states. ace-web reads that catalog at runtime
# (via SSM) so /api/mobile/states can return it to callers.
#
# Required env vars (passed in by Packer from the operator's environment):
#   COMMCARE_VERSIONS  TEST_PHONE_LOCAL  TEST_COUNTRY_CODE  TEST_PIN
#   TEST_BACKUP_CODE   TEST_NAME
set -euo pipefail

: "${COMMCARE_VERSIONS:?COMMCARE_VERSIONS is required}"
: "${TEST_PHONE_LOCAL:?TEST_PHONE_LOCAL is required}"
: "${TEST_COUNTRY_CODE:?TEST_COUNTRY_CODE is required}"
: "${TEST_PIN:?TEST_PIN is required}"
: "${TEST_BACKUP_CODE:?TEST_BACKUP_CODE is required}"
TEST_NAME="${TEST_NAME:-ACE Test User}"

# +7426 demo prefix sanity check on the *combined* number.
combined="${TEST_COUNTRY_CODE}${TEST_PHONE_LOCAL}"
case "$combined" in
  +7426*) ;;
  *)
    echo "ERROR: combined phone '$combined' is not in the +7426 demo range." >&2
    exit 1
    ;;
esac

ANDROID_SDK_ROOT=/opt/android-sdk
export ANDROID_SDK_ROOT
export ANDROID_HOME=/opt/android-sdk
export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/emulator:/usr/local/bin

AVD_NAME=ACE_Pixel_API_34
RECIPE_DIR=/opt/ace/recipes
APK_ROOT=/opt/ace/apks

# Stage recipes uploaded by Packer's file provisioner.
mkdir -p "$RECIPE_DIR"
cp -v /tmp/recipes/*.yaml "$RECIPE_DIR/"
chown -R ubuntu:ubuntu "$RECIPE_DIR"

# Iterate APK versions; bake one snapshot per.
IFS=',' read -ra VERSIONS <<< "$COMMCARE_VERSIONS"

# Build states.yaml header. Each successful bake appends an entry. The
# first listed version becomes the default state.
STATES_YAML=/opt/ace/states.yaml
{
  echo "# Auto-generated by 50-bake-snapshot.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
  echo "# Catalog of named AVD snapshots baked into this AMI."
  echo "default: cc-${VERSIONS[0]}"
  echo "states:"
} > "$STATES_YAML"

for VERSION in "${VERSIONS[@]}"; do
  VERSION="$(echo "$VERSION" | tr -d ' ')"
  STATE_NAME="cc-${VERSION}"
  SNAPSHOT_NAME="${STATE_NAME}-registered"
  APK_PATH="$APK_ROOT/$VERSION/commcare.apk"
  if [[ ! -f "$APK_PATH" ]]; then
    echo "ERROR: missing APK for $VERSION at $APK_PATH" >&2
    exit 1
  fi

  echo "===================================================================="
  echo "Baking snapshot for CommCare $VERSION → $SNAPSHOT_NAME"
  echo "===================================================================="

  sudo -u ubuntu -E bash <<EOF_INNER
set -euo pipefail
export ANDROID_SDK_ROOT=/opt/android-sdk
export ANDROID_HOME=/opt/android-sdk
export PATH=\$PATH:\$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:\$ANDROID_SDK_ROOT/platform-tools:\$ANDROID_SDK_ROOT/emulator:/usr/local/bin

# Cold boot — don't load any prior snapshot. Each version gets a fresh
# device state so we don't carry stale data across versions.
#
# Critical: do NOT pass -no-snapshot-save here. The 2026-05-09 bake
# investigation found that combining -no-snapshot-save with an explicit
# `adb emu avd snapshot save NAME` discards the userdata-qemu.img.qcow2
# overlay on emulator exit (kept in /tmp during the run, deleted on
# clean shutdown when -no-snapshot-save is set). The named snapshot's
# snapshot.pb references the now-missing qcow2, so only the 11-byte
# metadata file survives the AMI capture.
#
# Without -no-snapshot-save, QEMU folds the qcow2 back into the named
# snapshot's data files (ram.bin + disk delta) before exit, and the
# 3.4 GB snapshot dir survives the AMI capture intact. This is purely
# a bake-time concern; the runtime emulator (ace-emulator-launch)
# still uses -no-snapshot-save to keep each session read-only against
# the snapshot.
EMULATOR_LOG=/var/log/ace-mobile/bake-${VERSION}-emulator.log
nohup emulator -avd $AVD_NAME \
  -no-window -no-audio -no-metrics \
  -gpu swiftshader_indirect \
  -no-snapshot-load \
  -no-boot-anim \
  -wipe-data \
  > "\$EMULATOR_LOG" 2>&1 &
EMULATOR_PID=\$!
echo "emulator launched for $VERSION, pid=\$EMULATOR_PID, log=\$EMULATOR_LOG"

sleep 5
if ! kill -0 \$EMULATOR_PID 2>/dev/null; then
  echo "ERROR: emulator died before adb saw it. Log tail:" >&2
  tail -40 "\$EMULATOR_LOG" >&2 || true
  exit 1
fi

echo "Waiting for adb (max 180s)..."
if ! timeout 180 adb wait-for-device; then
  echo "ERROR: adb wait-for-device timed out. Log tail:" >&2
  tail -60 "\$EMULATOR_LOG" >&2 || true
  exit 1
fi

echo "Waiting for sys.boot_completed..."
boot_complete=""
for i in \$(seq 1 60); do
  boot_complete=\$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r' || true)
  if [[ "\$boot_complete" == "1" ]]; then break; fi
  sleep 5
done
if [[ "\$boot_complete" != "1" ]]; then
  echo "Boot timed out" >&2
  exit 1
fi

# Disable GMS, install APK, grant CAMERA, run recipes.
adb shell pm disable-user --user 0 com.google.android.gms || true
adb install -r "$APK_PATH"
adb shell pm grant org.commcare.dalvik android.permission.CAMERA || true

cd $RECIPE_DIR
maestro test connect-register-to-otp.yaml \
  --env COUNTRY_CODE='$TEST_COUNTRY_CODE' \
  --env PHONE_LOCAL='$TEST_PHONE_LOCAL' \
  --env PHONE='${TEST_COUNTRY_CODE}${TEST_PHONE_LOCAL}'

maestro test connect-register-from-otp.yaml \
  --env NAME='$TEST_NAME' \
  --env BACKUP_CODE='$TEST_BACKUP_CODE' \
  --env PIN='$TEST_PIN'

# Save the snapshot.
adb emu avd snapshot save $SNAPSHOT_NAME
adb emu avd snapshot list
adb emu kill
EOF_INNER

  # Wait for emulator to fully exit.
  for i in $(seq 1 30); do
    pgrep -f "emulator -avd $AVD_NAME" >/dev/null || break
    sleep 1
  done

  # Sync filesystem buffers BEFORE the AMI capture sees the volume. The
  # 2026-05-09 bake produced a snapshot that lacked CommCare on runtime;
  # most likely cause was unflushed userdata-qemu.img writes lost when
  # packer terminated the bake instance. Explicit `sync` here forces
  # the kernel to push the AVD's .img files to disk.
  sync
  sync # second sync is harmless and guards against rare device flushes

  # Append to states.yaml.
  CC_MD5="$(cat "$APK_ROOT/$VERSION/commcare.apk.md5")"
  cat >> "$STATES_YAML" <<YAML
  - name: ${STATE_NAME}
    snapshot: ${SNAPSHOT_NAME}
    commcare_version: "${VERSION}"
    commcare_apk_md5: ${CC_MD5}
    apk_path: ${APK_PATH}
    description: "CommCare ${VERSION} with +7426 demo user registered."
YAML

  echo "Snapshot for $VERSION baked + flushed."
done

# One final sync after the loop completes.
sync; sync

chown ubuntu:ubuntu "$STATES_YAML"

echo "===================================================================="
echo "Snapshot bake complete for ${#VERSIONS[@]} version(s)."
cat "$STATES_YAML"
echo "===================================================================="
