#!/bin/bash
# Build /opt/ace/states.yaml describing the named states (one per
# CommCare APK version) baked into this AMI. ace-web reads it via SSM
# (GET /api/mobile/states) and ace-emulator-launch reads it on cold
# boot to pick which APK to install.
#
# This step USED to bake AVD snapshots with the demo user pre-registered;
# we removed that path on 2026-05-10 — the snapshot data didn't survive
# AMI capture, and runtime cold-boot + register is fast enough (~2-3 min)
# that the architectural simplification is worth it. See
# docs/learnings/cloud-emulator-snapshot-persistence.md for the
# investigation; docs/specs/2026-05-10-phase5-cloud-mobile-integration-design.md
# for the design rationale.
#
# This script is idempotent and reads COMMCARE_VERSIONS from Packer's
# environment (the same var that drove 40-commcare-apk.sh).
set -eu

: "${COMMCARE_VERSIONS:?COMMCARE_VERSIONS is required}"

APK_ROOT=/opt/ace/apks
RECIPE_DIR=/opt/ace/recipes
STATES_YAML=/opt/ace/states.yaml

# Stage Maestro recipes Packer's file provisioner copied to /tmp.
mkdir -p "$RECIPE_DIR"
cp -v /tmp/recipes/*.yaml "$RECIPE_DIR/"
chown -R ubuntu:ubuntu "$RECIPE_DIR"

IFS=',' read -ra VERSIONS <<< "$COMMCARE_VERSIONS"

# states.yaml header + entry per version.
{
  echo "# Auto-generated by 50-bake-snapshot.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
  echo "# Catalog of named states (= CommCare APK versions) the runner can register."
  echo "# Default = first version listed; ace-emulator-launch picks it on cold boot."
  echo "default: cc-${VERSIONS[0]}"
  echo "states:"
} > "$STATES_YAML"

for VERSION in "${VERSIONS[@]}"; do
  VERSION="$(echo "$VERSION" | tr -d ' ')"
  STATE_NAME="cc-${VERSION}"
  APK_PATH="$APK_ROOT/$VERSION/commcare.apk"
  if [[ ! -f "$APK_PATH" ]]; then
    echo "ERROR: missing APK for $VERSION at $APK_PATH" >&2
    exit 1
  fi
  CC_MD5="$(cat "$APK_PATH.md5")"

  cat >> "$STATES_YAML" <<YAML
  - name: ${STATE_NAME}
    snapshot: cold-boot-register
    commcare_version: "${VERSION}"
    commcare_apk_md5: ${CC_MD5}
    apk_path: ${APK_PATH}
    description: "CommCare ${VERSION} — cold boot + register on every cold start (~2-3 min)."
YAML
done

chown ubuntu:ubuntu "$STATES_YAML"

echo "===================================================================="
echo "States manifest built for ${#VERSIONS[@]} version(s):"
cat "$STATES_YAML"
echo "===================================================================="
