# Generated by Django 5.2.13 on 2026-05-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_workspaces', '0002_seed_dimagi_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='auto_join_domains',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
