# Generated by Django 5.2.17 on 2026-09-28 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ace_workspaces", "0006_dimagi_associate_auto_join"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="default_tenancy",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="TenancyChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opp_slug", models.CharField(blank=True, default="", max_length=64)),
                ("before", models.JSONField(default=dict)),
                ("after", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenancy_changes",
                        to="ace_workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "workspace_tenancy_changes",
                "indexes": [
                    models.Index(
                        fields=["workspace", "-created_at"],
                        name="workspace_t_workspa_313f03_idx",
                    )
                ],
            },
        ),
    ]
