# Generated by Django 5.2.17 on 2026-09-28 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ace_workspaces", "0007_tenancy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RunClone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opp_slug", models.CharField(max_length=64)),
                ("run_id", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("copying", "Copying"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        default="copying",
                        max_length=16,
                    ),
                ),
                ("files_copied", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clones_out",
                        to="ace_workspaces.workspace",
                    ),
                ),
                (
                    "target_workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clones_in",
                        to="ace_workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "workspace_run_clones",
                "indexes": [
                    models.Index(
                        fields=["source_workspace", "opp_slug", "run_id"],
                        name="workspace_r_source__7819c9_idx",
                    ),
                    models.Index(
                        fields=["target_workspace", "opp_slug", "run_id"],
                        name="workspace_r_target__b43631_idx",
                    ),
                ],
            },
        ),
    ]
