# Generated by Django 5.2.13 on 2026-10-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ace_workspaces", "0010_canopy_probe_principal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspaceinvite",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                    ("editor", "Editor"),
                    ("viewer", "Viewer"),
                ],
                default="editor",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="workspacemembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                    ("editor", "Editor"),
                    ("viewer", "Viewer"),
                ],
                max_length=16,
            ),
        ),
    ]
