# Generated by Django 5.2.13 on 2026-04-08 10:16

import apps.sessions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=apps.sessions.models.generate_slug, max_length=32, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('backend_kind', models.CharField(choices=[('cli', 'CLI (subscription)'), ('api', 'API (key)'), ('mcp', 'MCP-augmented API')], default='cli', max_length=16)),
                ('backend_config', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('imported', 'Imported')], default='active', max_length=16)),
                ('source', models.CharField(choices=[('web', 'Web'), ('upload', 'Upload')], default='web', max_length=16)),
                ('opportunity_id', models.BigIntegerField(blank=True, null=True)),
                ('ocs_agent_id', models.CharField(blank=True, max_length=200, null=True)),
                ('idd_ref', models.CharField(blank=True, max_length=500, null=True)),
                ('cli_session_id', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_index', models.IntegerField()),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool_use', 'Tool use'), ('tool_result', 'Tool result')], max_length=16)),
                ('content', models.JSONField()),
                ('plaintext', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('streaming', 'Streaming'), ('complete', 'Complete'), ('error', 'Error')], default='pending', max_length=16)),
                ('error_detail', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ace_sessions.session')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['session_id', 'turn_index'],
            },
        ),
        migrations.CreateModel(
            name='IngestUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.CharField(blank=True, default='', max_length=1000)),
                ('raw_bytes', models.BigIntegerField(default=0)),
                ('line_count', models.IntegerField(default=0)),
                ('cli_session_id', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingest_records', to='ace_sessions.session')),
            ],
            options={
                'db_table': 'ingest_uploads',
            },
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('next', 'Next'), ('queued', 'Queued')], default='queued', max_length=8)),
                ('queue_position', models.IntegerField(blank=True, null=True)),
                ('body', models.TextField(blank=True, default='')),
                ('version', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('sent', 'Sent'), ('discarded', 'Discarded')], default='open', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_drafts', to=settings.AUTH_USER_MODEL)),
                ('last_editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edited_drafts', to=settings.AUTH_USER_MODEL)),
                ('sent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_draft', to='ace_sessions.message')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='ace_sessions.session')),
            ],
            options={
                'db_table': 'drafts',
            },
        ),
        migrations.CreateModel(
            name='SessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='editor', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='ace_sessions.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'session_participants',
            },
        ),
        migrations.CreateModel(
            name='ShareToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=apps.sessions.models.generate_share_token, max_length=64, unique=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='share_tokens', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_tokens', to='ace_sessions.session')),
            ],
            options={
                'db_table': 'share_tokens',
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['status', '-created_at'], name='sessions_status_fb16d3_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['owner', '-created_at'], name='sessions_owner_i_34daa7_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('session', 'turn_index'), name='unique_session_turn'),
        ),
        migrations.AddConstraint(
            model_name='draft',
            constraint=models.UniqueConstraint(condition=models.Q(('slot', 'next'), ('status', 'open')), fields=('session',), name='one_next_per_session'),
        ),
        migrations.AddIndex(
            model_name='sessionparticipant',
            index=models.Index(fields=['session', 'last_seen_at'], name='session_par_session_ec7073_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessionparticipant',
            constraint=models.UniqueConstraint(fields=('session', 'user'), name='unique_participant'),
        ),
    ]
