# Generated by Django 5.2.13 on 2026-04-09 05:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='opp_run_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='session',
            name='opp_slug',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='session',
            name='opp_step_skill',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['opp_slug', 'opp_run_id', 'opp_step_skill'], name='idx_session_opp_step'),
        ),
    ]
