# Generated by Django 5.2.13 on 2026-04-27 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_sessions', '0003_backfill_owner_participant'),
        ('ace_workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestupload',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingest_uploads', to='ace_workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='session',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='ace_workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='sharetoken',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_tokens', to='ace_workspaces.workspace'),
        ),
    ]
