# Generated by Django 5.2.13 on 2026-05-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_sessions', '0004_ingestupload_workspace_session_workspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='cost_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
