# Generated by Django 5.2.13 on 2026-05-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_sessions', '0005_session_cost_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestupload',
            name='content_sha256',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
