# Generated by Django 5.2.13 on 2026-05-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_sessions', '0006_ingestupload_content_sha256'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestupload',
            name='raw_jsonl_gz',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
