# Generated by Django 5.2.15 on 2026-06-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_sessions', '0007_ingestupload_raw_jsonl_gz'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='driver_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
