# Generated by Django 5.2.13 on 2026-07-26 10:32
"""Drop the `drafts` and `share_tokens` tables.

Both backed chat-UI-only features (co-edited next-message drafts, and
session share links) retired alongside apps/sessions/{consumers,drafts,
presence,routing}.py in favor of canopy-hosted chat. The `sessions`,
`session_participants`, and `messages` tables are DELIBERATELY NOT touched
here — Session/Message are still live production infrastructure for
programmatic ACE runs (apps.opps.api::seeded_run — MCP-exposed, the
drive_turn management command, Slack-triggered runs, the post-deploy
resume-interrupted self-heal) as well as apps.ingest, apps.activity, and
apps.slack. See the retirement PR's description for the full dependency
map and that judgment call.
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ace_sessions', '0008_session_driver_heartbeat_at'),
        # apps/workspaces/migrations/0002_seed_dimagi_team.py's RunPython
        # data migration does `apps.get_model("ace_sessions", "ShareToken")`
        # against the historical migration state. Without this explicit
        # edge, Django's topological sort is free to run this DeleteModel
        # before that RunPython (both only formally depend on
        # ace_sessions/0004), which raises `LookupError: App 'ace_sessions'
        # doesn't have a 'ShareToken' model` on a fresh migrate. Pin the
        # order instead.
        ('ace_workspaces', '0002_seed_dimagi_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharetoken',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sharetoken',
            name='session',
        ),
        migrations.RemoveField(
            model_name='sharetoken',
            name='workspace',
        ),
        migrations.DeleteModel(
            name='Draft',
        ),
        migrations.DeleteModel(
            name='ShareToken',
        ),
    ]
