# Generated by Django 5.2.16 on 2026-07-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_sessions', '0009_retire_draft_and_sharetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='canopy_turn_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='session',
            name='canopy_session_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
