# Generated by Django 5.2.13 on 2026-07-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_sessions', '0010_canopy_run_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestupload',
            name='canopy_turn_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ingestupload',
            name='source',
            field=models.CharField(choices=[('local', 'Local'), ('canopy', 'Canopy')], default='local', max_length=16),
        ),
    ]
