# Generated by Django 5.2.17 on 2026-10-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ace_sessions", "0011_ingestupload_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="requested_by",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
